import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>@ms.hopy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" 
          width={4}
          height={4}
          priority />
        <link href="https://fonts.googleapis.com/css2?family=Roboto&amp;display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&amp;display=swap" rel="stylesheet"/>
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
             
            </a>
          </div>
        </div> */}

        <div className={styles.center}>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div> */}
        </div>

        <div className={styles.grid}>
          <a
            href="/mi-ukelele"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              El ukelele 
            </h2>
            <p className={inter.className}>
              Conoce los tipos de ukelele, los acordes, aprende... 
            </p>
          </a>

          <a
            href="/cancioneros"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Cancioneros 
            </h2>
            <p className={inter.className}>
              Tablaturas de mis canciones favoritas...
            </p>
          </a>

          <a
            href="/informacion"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Info interesante 
            </h2>
            <p className={inter.className}>
              Seccion clubs, tiendas, etc.
            </p>
          </a>

          <a
            href="/algo"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Algo 
            </h2>
            <p className={inter.className}>
              Otra seccion...
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
